# Generated by Django 4.1.1 on 2022-12-26 10:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[(1, 'Gpay'), (2, 'paytm'), (3, 'upi')], max_length=20)),
                ('p_upi_id', models.CharField(max_length=30)),
                ('p_time', models.DateTimeField(default=datetime.datetime(2022, 12, 26, 15, 59, 20, 130411))),
                ('p_price', models.IntegerField()),
            ],
        ),
    ]
