# Generated by Django 4.1.1 on 2022-12-31 05:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='p_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 31, 11, 5, 57, 872339)),
        ),
    ]
