# Generated by Django 4.1.1 on 2023-01-04 07:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0015_alter_payment_p_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='p_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 4, 13, 28, 29, 620239)),
        ),
    ]
