# Generated by Django 4.1.1 on 2023-01-10 05:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0017_remove_payment_payment_method_payment_p_booking_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='p_price',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='p_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 10, 11, 12, 17, 820722)),
        ),
    ]
