# Generated by Django 4.1.1 on 2023-01-10 05:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0027_alter_booking_booking_time'),
        ('payment', '0018_alter_payment_p_price_alter_payment_p_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='p_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='p_booking_id',
            field=models.ForeignKey(default=21, on_delete=django.db.models.deletion.CASCADE, to='booking.booking'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='p_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 10, 11, 24, 1, 521768)),
        ),
    ]
