# Generated by Django 4.1.1 on 2022-12-25 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='theatre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theatre_name', models.CharField(default='The mall', max_length=100)),
                ('theatre_add', models.TextField(default='malad', max_length=1000)),
                ('theatre_loc', models.CharField(default='malad', max_length=20)),
                ('no_of_theatre', models.IntegerField(default=5)),
            ],
        ),
    ]
