# Generated by Django 4.1.1 on 2022-12-26 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='theatre',
            old_name='no_of_theatre',
            new_name='no_of_halls',
        ),
    ]
