# Generated by Django 4.1.1 on 2022-12-24 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theatre',
            name='theatre_capacity',
        ),
        migrations.AddField(
            model_name='theatre',
            name='theatre_loc',
            field=models.CharField(default='malad', max_length=20),
        ),
        migrations.AlterField(
            model_name='theatre',
            name='no_of_theatre',
            field=models.IntegerField(default=5),
        ),
    ]
