# Generated by Django 4.1.1 on 2022-11-01 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoL', '0003_alter_user_imgs'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='status',
            field=models.BooleanField(choices=[('pending', 'pending'), ('completed', 'completed')], default=0),
        ),
        migrations.AlterField(
            model_name='list',
            name='desc',
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name='list',
            name='end',
            field=models.DateTimeField(default=0),
        ),
        migrations.AlterField(
            model_name='list',
            name='start',
            field=models.DateTimeField(default=0),
        ),
    ]
