# Generated by Django 4.1.1 on 2022-11-01 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoL', '0004_list_status_alter_list_desc_alter_list_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='status',
            field=models.BooleanField(choices=[('p', 'pending'), ('c', 'completed')], default=0),
        ),
    ]
