# Generated by Django 4.1.1 on 2022-11-01 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoL', '0005_alter_list_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='status',
            field=models.BooleanField(default=0),
        ),
    ]
