# Generated by Django 4.1.1 on 2022-11-01 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoL', '0006_alter_list_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='desc',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='list',
            name='end',
            field=models.DateTimeField(default=''),
        ),
        migrations.AlterField(
            model_name='list',
            name='start',
            field=models.DateTimeField(default=''),
        ),
        migrations.AlterField(
            model_name='list',
            name='status',
            field=models.BooleanField(choices=[('p', False), ('c', True)], default=False),
        ),
    ]
