# Generated by Django 4.1.1 on 2022-11-01 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoL', '0007_alter_list_desc_alter_list_end_alter_list_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='status',
            field=models.BooleanField(choices=[(False, 'pending'), (True, 'completed')], default=False),
        ),
    ]
