# Generated by Django 4.1.1 on 2022-11-01 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoL', '0008_alter_list_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.BooleanField(choices=[(False, 'pending'), (True, 'completed')], default=False),
        ),
    ]
