# Generated by Django 4.1.1 on 2022-11-01 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todoL', '0011_delete_abc_task_user_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='user_fk',
            field=models.ForeignKey(default='dc', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
