# Generated by Django 4.1.1 on 2022-11-02 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoL', '0012_alter_task_user_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='dcchawda2003@gmail.com', max_length=254),
        ),
    ]
