# Generated by Django 4.1.1 on 2022-11-07 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoL', '0018_list_user_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='imgs',
            field=models.ImageField(null=True, upload_to='image/'),
        ),
    ]
