# Generated by Django 4.1.1 on 2022-12-24 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('theatre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=100)),
                ('movie_no', models.CharField(max_length=100, unique=True)),
                ('movie_time', models.DateTimeField()),
                ('movie_lang', models.CharField(max_length=50)),
                ('movie_type', models.CharField(max_length=50)),
                ('movie_rating', models.IntegerField(default=17)),
                ('movie_hrs', models.TimeField()),
                ('movie_ticket_price', models.IntegerField(default=100)),
                ('theatre_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theatre.theatre')),
            ],
        ),
    ]
