# Generated by Django 4.1.1 on 2022-12-24 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_hrs',
            field=models.IntegerField(default=2),
        ),
    ]
