# Generated by Django 4.1.1 on 2022-12-25 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_alter_movie_movie_hrs'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='no_of_seats',
            field=models.IntegerField(default=50),
        ),
    ]
