# Generated by Django 4.1.1 on 2023-02-16 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mob',
            field=models.IntegerField(default=9000000000),
        ),
    ]
