# Generated by Django 4.1.1 on 2022-12-24 06:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapi', '0003_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mob',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(10)]),
        ),
    ]
