# Generated by Django 4.1.1 on 2022-12-24 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapi', '0004_user_mob'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=17),
        ),
    ]
