# Generated by Django 4.1.1 on 2023-01-01 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapi', '0005_user_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_movie_operator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_theatre_operator',
            field=models.BooleanField(default=False),
        ),
    ]
