# Generated by Django 4.1.1 on 2023-01-03 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicapi', '0010_alter_user_mob'),
    ]

    operations = [
        migrations.DeleteModel(
            name='article',
        ),
        migrations.DeleteModel(
            name='movie',
        ),
    ]
