# Generated by Django 4.1.1 on 2023-01-03 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicapi', '0012_theatreuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='theatreuser',
            options={'permissions': (('theatre.view_theatre', 'can view theatre of theatre'),)},
        ),
    ]
