# Generated by Django 4.1.1 on 2023-01-04 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicapi', '0013_alter_theatreuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='theatreuser',
            options={},
        ),
    ]
